include:
  - project: 'ericvh/gitlab-ci-arm-template'
    file: '/.gitlab-ci.yml'

variables:
  CI_BUILDX_ARCHS: "linux/amd64,linux/arm64,linux/arm"

# extra build for the Nvidia version
build:buildx-xavier:
  extends: .build
  only:
    variables:
      - $CI_BUILDX_ARCHS
  except:
    refs:
       - master
  timeout: 3 hours
  script:
    - update-binfmts --enable # Important: Ensures execution of other binary formats is enabled in the kernel
    - docker buildx create --driver docker-container --use
    - docker buildx inspect --bootstrap
    - docker buildx ls
    - docker buildx build -f Dockerfile-xavier --platform linux/arm64 --progress plain --pull -t "$CI_APPLICATION_REPOSITORY:${CI_APPLICATION_TAG}_xavier" --push .
